### ISSUE TITLE
Cargo duplication

### ISSUE THREAD

**Issue by 100petr** [J3fftw1/HeadLimiter#3]
Place the maximum number of cargo (heads) in the chunk
Place another above the limit on the ground
You get extra cargo
Video: https://youtu.be/HoV60eTD_50
![image](https://user-images.githubusercontent.com/29830635/111484906-74a6bc00-8736-11eb-89d2-8b1ec69e88f5.png)

**Comment by J3fftw1** [comment]
please give a pastebin of the error.

**Comment by 100petr** [comment]
No error in console. https://pastebin.com/9TBbCrPu

**Comment by variananora** [comment]
hope this extra info helped.

Steps to reproduce the Issue
1. Exceed the head cargo limit in 1 chunk
2. Place a cargo node input or output on the ground (or anything except machine or inventory based blocks)
3. The cargo placement is canceled but also dropping duplicate one on the ground.

Video:


https://user-images.githubusercontent.com/34732414/111486301-f49a4980-8769-11eb-841b-d25ac80187a7.mp4


Expected behavior:
The cargo placement should not be dropped on the ground

No errors/logs that would be useful.

Environment:
![image](https://user-images.githubusercontent.com/34732414/111486076-c0268d80-8769-11eb-886d-afcf92233a05.png)
